# Install script for directory: /Users/noisyedge/Projects/mdl-source/MDL-SDK

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/usr/local")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/include/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/src/base/system/main/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/src/base/system/stlext/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/src/base/system/version/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/src/base/lib/libzip/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/src/base/lib/zlib/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/src/base/lib/tinyxml2/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/src/mdl/compiler/coco/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/src/mdl/jit/llvm/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/src/base/util/string_utils/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/src/base/util/registry/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/src/base/hal/disk/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/src/base/hal/hal/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/src/base/hal/link/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/src/base/hal/time/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/src/base/lib/config/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/src/base/lib/cont/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/src/base/lib/log/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/src/base/lib/mem/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/src/base/lib/path/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/src/base/lib/plug/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/src/base/data/attr/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/src/base/data/db/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/src/base/data/dblight/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/src/base/data/serial/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/src/io/image/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/src/io/scene/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/src/api/api/mdl/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/src/mdl/codegenerators/generator_code/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/src/mdl/codegenerators/generator_dag/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/src/mdl/compiler/compilercore/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/src/mdl/compiler/compiler_hlsl/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/src/mdl/jit/libbsdf/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/src/mdl/jit/devlib/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/src/mdl/jit/generator_jit/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/src/mdl/no_glsl/generator_stub/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/src/mdl/no_jit/generator_stub/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/src/mdl/runtime/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/src/mdl/integration/i18n/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/src/mdl/integration/mdlnr/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/src/render/mdl/backends/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/src/render/mdl/runtime/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/src/prod/lib/mdl_core/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/src/prod/lib/mdl_sdk/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/src/prod/bin/i18n/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/src/prod/bin/mdlc/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/src/prod/bin/mdlm/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/src/shaders/plugin/dds/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/src/shaders/plugin/freeimage/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/examples/thirdparty/imgui/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/examples/thirdparty/tinyxml2/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/examples/mdl_sdk/shared/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/examples/mdl_sdk/archives/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/examples/mdl_sdk/calls/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/examples/mdl_sdk/compilation/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/examples/mdl_sdk/discovery/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/examples/mdl_sdk/execution_native/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/examples/mdl_sdk/generate_mdl_identifier/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/examples/mdl_sdk/instantiation/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/examples/mdl_sdk/mdle/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/examples/mdl_sdk/modules/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/examples/mdl_sdk/start_shutdown/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/examples/mdl_sdk/traversal/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/examples/mdl_sdk/mdl_browser/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/examples/mdl_core/shared/cmake_install.cmake")
  include("/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/examples/mdl_core/calls/cmake_install.cmake")

endif()

if(CMAKE_INSTALL_COMPONENT)
  set(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INSTALL_COMPONENT}.txt")
else()
  set(CMAKE_INSTALL_MANIFEST "install_manifest.txt")
endif()

string(REPLACE ";" "\n" CMAKE_INSTALL_MANIFEST_CONTENT
       "${CMAKE_INSTALL_MANIFEST_FILES}")
file(WRITE "/Users/noisyedge/Projects/mdl-source/MDL-SDK/build_ninja/${CMAKE_INSTALL_MANIFEST}"
     "${CMAKE_INSTALL_MANIFEST_CONTENT}")
